### ISSUE TITLE
Repeated function definitions in the REPL trigger an ICE

### ISSUE THREAD

**Issue by waterlens** [effekt-lang/effekt#167] opened 2022-10-26 15:26 UTC
Version: 0.2.0

After I typed the same function definition two times, the REPL crashed and reported an ICE.
```
> def f() = ()
f: () => Unit
> def f() = ()
Exception in thread "main" PlainTextError(Internal Compiler Error: Cannot find symbol for IdDef(f),None,Error)
        at effekt.util.messages$CompilerPanic$.apply(Messages.scala:37)
        at effekt.util.messages$ErrorReporter.panic(Messages.scala:97)
        at effekt.util.messages$ErrorReporter.panic$(Messages.scala:76)
        ...
```

**Comment by b-studios** [comment] 2022-11-04 10:11
Hey, thanks for reporting! This looks like a duplicate of #77

**Closed by b-studios** 2022-11-04 10:11 UTC
