### ISSUE TITLE
Broken link in Readme 'Installation' section for "getting-started guide"

### ISSUE THREAD

**Issue by JakubSchwenkbeck** [effekt-lang/effekt#672] opened 2024-11-06 20:23 UTC
**Description**  
In the `Installation` section of the Readme, the link for the "getting-started guide" currently redirects to [https://effekt-lang.org/docs/getting-started#installing-effekt](https://effekt-lang.org/docs/getting-started#installing-effekt), which results in a 404 error.

Could this link be updated to the correct URL, or could you provide an alternative if the guide has moved? 

As I see it, [https://effekt-lang.org/docs](https://effekt-lang.org/docs) is the path which leads to the `Getting Started` section of the Docs, while  [https://effekt-lang.org/docs/getting-started](https://effekt-lang.org/docs/getting-started) does not exist (anymore?).

All other sections in the Docs have an own (and working) path for the URL

**Comment by jiribenes** [comment] 2024-11-06 20:37
Hi @JakubSchwenkbeck, thank you for the detailed report!

This is a duplicate of an issue https://github.com/effekt-lang/effekt-website/issues/78 already reported on the repository [`effekt-lang/effekt-website`](https://github.com/effekt-lang/effekt-website/) that we use for website-related development.

I put the `good-first-issue` onto the original issue, feel free to tackle it if you're interested in contributing. :)

**Closed by jiribenes** 2024-11-06 20:37 UTC
