### ISSUE TITLE
There should be an option to produce an executable without running it

### ISSUE THREAD

**Issue by phischu** [effekt-lang/effekt#273] opened 2023-07-11 11:25 UTC
Currently invoking `effekt main.effekt` will compile and run the given file and `effekt --compile main.effekt` will just generate code and then stop.

For the llvm backend (and also the mlton backend) it would be great if it was possible to also invoke the llvm compiler (respectively mlton compiler) to produce an executable but then not run it.

**Comment by b-studios** [comment] 2023-07-11 11:36
I agree, `--compile` should do exactly that.

**Comment by b-studios** [comment] 2023-10-10 13:25
Duplicate of #254

**Closed by b-studios** 2023-10-10 13:25 UTC
Labels: enhancement, good first issue
