### ISSUE TITLE
--build flag missing in 0.2.1

### ISSUE THREAD

**Issue by IR0NSIGHT** [effekt-lang/effekt#358] opened 2024-01-16 10:04 UTC
on the lastest master i can use --build or -b to build an executable on my effekt script. (That way i can use commandline arguments)
this flag has existed since at least since commit cbff76e875c7ce4aca5e52fd8ef170c1f66b97e9
<https://github.com/effekt-lang/effekt/commit/cbff76e875c7ce4aca5e52fd8ef170c1f66b97e9>

I could not find docu on when it was added

on 0.2.1 clean new install -b is missing:
```
max-priv@NOAH367-L:~/Dokumente/repos/effekt$ effekt.sh -h
      --backend  <arg>        The backend that should be used Choices: js,
                              chez-callcc, chez-monadic, chez-lift, llvm, ml
  -c, --compile               Compile the Effekt program
      --nocompile             Run the effekt program in the interpreter
      --includes  <arg>...    Path to consider for includes (can be set multiple
                              times)
  -l, --lib  <arg>            Path to the standard library to be used
      --llvm-version  <arg>   the llvm version that should be used to compile
                              the generated programs (only necessary if backend
                              is llvm, defaults to 15)
  -o, --out  <arg>            Path to write generated files to (defaults to
                              ./out)
      --prelude  <arg>...     Modules to be automatically imported in every
                              file.
  -s, --server                Run compiler as a language server
      --noserver              Run compiler in standard batch mode
  -h, --help                  Show help message

 trailing arguments:
  files (not required)   Input files
max-priv@NOAH367-L:~/Dokumente/repos/effekt$ effekt.sh -b ./doesntExist.effekt
Unknown option 'b'
```

According to @phischu the option should be present on 0.2.1

If not, is there an easy workaround to use commandline arguments on 0.2.1?

**Comment by jiribenes** [comment] 2024-01-16 10:49
The `--build` flag seems to have only been added in https://github.com/effekt-lang/effekt/commit/dc507aa74d765a17e5fe58b230e8fd8d3e3ac88d (Oct 18, 2023), whereas [v0.2.1](https://github.com/effekt-lang/effekt/releases/tag/v0.2.1) was released on Sep 24, 2023.

**Comment by b-studios** [comment] 2024-01-28 08:59
The corresponding option is defined here:

https://github.com/effekt-lang/effekt/blob/3aa78e8795b8adb1d347827a3f2b004c2b783be2/effekt/jvm/src/main/scala/effekt/EffektConfig.scala#L19-L23

We should make a new release soon, but can you locally install effekt from source for now?

```
sbt install
```

Closing this, since this is not a bug in itself.

**Closed by b-studios** 2024-01-28 08:59 UTC
Labels: bug
