### ISSUE TITLE
Unexpected Reference Error, when working with Coroutines.

### ISSUE THREAD

**Issue by matthias-dunkel** [effekt-lang/effekt#249] opened 2023-03-24 12:49 UTC
### Code to reproduce
```
type Coroutine[A] {
    Done()
    More(f: A => Coroutine[A] at {})
}

def createCoroutine(): Coroutine[String] = {
    var cr = Done();
    cr = More(
            fun(s:String){
                    Done()
                }
            )
    cr
}

def work{cr: => Coroutine[String]} = {
    var coroutine = cr();
    ()
}

def main() = {
    work{createCoroutine()}
}
```
### Expected Output
Nothing. Should terminate.

### Actual Output
```
const coroutine = $this.fresh(tmp378);
ReferenceError: $this is not defined
```

### The compiled work function, where the undefined this lives.
```
function work(cr) {
    return cr().then(((tmp378) =>
        (() =>
            {
                const coroutine = $this.fresh(tmp378);
                
                return $effekt.pure($effekt.unit);
            })()));
}
```
Is this a compiler error, or am I doing something wrong?

**Comment by matthias-dunkel** [comment] 2023-03-24 13:50
I do not know why. But changing the `work` function to this:
```
def work(cr: Coroutine[String]) = {
    var coroutine = Done();
    coroutine = cr
}
```
"solves" the bug.

**Comment by b-studios** [comment] 2023-03-24 13:52
Looks like a problem where the region for mutable state is inferred incorrectly.  Here is the core representation:

```
def createCoroutine() =
  region { (this) => 
    let tmp476 = Done()
    
    var cr in this = tmp476 ;
    let _ = cr.put(More((box { (s) => 
      Done()
    })));
    let tmp477 = cr.get()
    
    tmp477
  };
def work(cr) =
  val tmp482 = cr();
  var coroutine in this = tmp482 ;
  ();
def main() = work({ () =>  createCoroutine() })
```
We can see that indeed a `region { (this) => ... }` is missing around the body of `work`.

**Comment by b-studios** [comment] 2023-03-24 13:54
As a more reasonable workaround, you should be able to provide the region explicitly:

```
def work{cr: => Coroutine[String]} = region this {
    var coroutine in this = cr();
    ()
}
```

The bug is related to this function (I guess): 
https://github.com/effekt-lang/effekt/blob/master/effekt/shared/src/main/scala/effekt/source/ExplicitRegions.scala#L29

**Comment by b-studios** [comment] 2023-03-24 13:55
Eventually in #235 we might solve this bug since we change how local mutable state is represented. @matthias-dunkel  could you maybe try to checkout #235 and see what the output is? That would be helpful.

**Comment by matthias-dunkel** [comment] 2023-03-24 14:00
I tried it on #235. It still is not working, and here is the output:
```
function work(cr) {
    const tmp369 = cr;
    
    const coroutine = $this.fresh(tmp369);
    
    return $effekt.pure(cr);
}
```

**Comment by matthias-dunkel** [comment] 2023-03-24 14:13
This will also reproduce the error:
```
def main()={
 var i = 1;
 ()
}
```

**Comment by b-studios** [comment] 2023-03-24 14:15
Ha, ok thanks. That solves it ;) Then it is a problem with capture inference. Since you do not use `i` it is not registered to be required and the region is not introduced.

**Comment by b-studios** [comment] 2023-03-24 14:16
It is a bit strange since here we say that we need the region:

https://github.com/effekt-lang/effekt/blob/master/effekt/shared/src/main/scala/effekt/Typer.scala#L702

**Comment by b-studios** [comment] 2023-03-29 12:19
@matthias-dunkel I just tried to reproduce your reported error, but it just works for me on master and on naive-state. Can you help me reproduce it somehow? What are the exact steps I have to take?

**Comment by b-studios** [comment] 2023-04-01 08:00
I am closing this issue since it seems to work on master. If you encounter it again, feel free to reopen.

**Closed by b-studios** 2023-04-01 08:00 UTC
